version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --bind 0.0.0.0 --protected-mode no --requirepass your_password

volumes:
  redis-data:
    driver: local
